/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.User_Controller;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import models.User_Model;

/**
 *
 * @author MANALI
 */
public class Admin_View extends javax.swing.JFrame {

    /**
     * Creates new form Admin_View
     */
    public User_Controller controller = null;
    private int user_id;

    public Admin_View() {
        controller = new User_Controller();
        controller.cregform = this;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Admin_View(int uid){
        user_id = uid;
        controller = new User_Controller();
        controller.cregform = this;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add_c_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        add_c_lname = new javax.swing.JTextField();
        add_c_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        add_c_pswd = new javax.swing.JPasswordField();
        add_c_cpswd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add_c_phno = new javax.swing.JFormattedTextField();
        btn_c_register = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        del_c_id = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        del_c_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        del_c_phno = new javax.swing.JTextField();
        btn_del_coordinator = new javax.swing.JButton();
        del_c_name = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel3.setText("Coordinator Registration Form");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("First Name:");

        add_c_fname.setToolTipText("");
        add_c_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_c_fnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Last Name:");

        add_c_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_c_lnameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Email Address:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Confirn Password:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Phone Number:");

        add_c_phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_c_phnoActionPerformed(evt);
            }
        });

        btn_c_register.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_c_register.setText("Register");
        btn_c_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_c_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(add_c_lname)
                                    .addComponent(add_c_email)
                                    .addComponent(add_c_pswd)
                                    .addComponent(add_c_cpswd)
                                    .addComponent(add_c_phno)
                                    .addComponent(add_c_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(btn_c_register, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(add_c_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(add_c_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(add_c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(add_c_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(add_c_cpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(add_c_phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btn_c_register)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Coordinator", jPanel2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Name:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("ID:");

        del_c_id.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Email:");

        del_c_email.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Phone No:");

        del_c_phno.setEditable(false);

        btn_del_coordinator.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_del_coordinator.setText("Delete Coordinator");
        btn_del_coordinator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_coordinatorActionPerformed(evt);
            }
        });

        del_c_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        del_c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_c_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(del_c_id)
                            .addComponent(del_c_email)
                            .addComponent(del_c_phno)
                            .addComponent(del_c_name, 0, 196, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btn_del_coordinator)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(del_c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(del_c_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(del_c_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(del_c_phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btn_del_coordinator)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Coordinator", jPanel3);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("Sports Management System");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel2.setText("Manage Coordinators");

        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_logout))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        System.out.println("Tab changed to: " + sourceTabbedPane.getTitleAt(index));
        paneChangedSetUI(index);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void del_c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_c_nameActionPerformed
        // TODO add your handling code here:
        delCoordinatorSetUI();
    }//GEN-LAST:event_del_c_nameActionPerformed

    private void btn_del_coordinatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_coordinatorActionPerformed
        // TODO add your handling code here:
        controller.deleteCoordinator((User_Model) del_c_name.getSelectedItem());
        del_c_name.removeItemAt(del_c_name.getSelectedIndex());
    }//GEN-LAST:event_btn_del_coordinatorActionPerformed

    private void btn_c_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c_registerActionPerformed
        // TODO add your handling code here:
        String fname = add_c_fname.getText();
        String lname = add_c_lname.getText();
        String email = add_c_email.getText();
        String pswd = add_c_pswd.getText();
        String cpswd = add_c_cpswd.getText();
        String phno = add_c_phno.getText();

        if (this.validateCRegistrationForm(fname, lname, email, pswd, cpswd, phno)) {
            controller.registerCoordinator(fname, lname, email, pswd, phno);
        }
        add_c_fname.setText("");
        add_c_lname.setText("");
        add_c_email.setText("");
        add_c_pswd.setText("");
        add_c_cpswd.setText("");
        add_c_phno.setText("");
    }//GEN-LAST:event_btn_c_registerActionPerformed

    private void add_c_phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_c_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_c_phnoActionPerformed

    private void add_c_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_c_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_c_lnameActionPerformed

    private void add_c_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_c_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_c_fnameActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        Login_View login=new Login_View();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private boolean validateCRegistrationForm(String fname, String lname, String email, String pswd, String cpswd, String phno) {
        if (fname.equals("")) {
            this.showMsg("First Name is empty");
            return false;
        }
        if (lname.equals("")) {
            this.showMsg("Last Name is empty");
            return false;
        }
        if (email.equals("")) {
            this.showMsg("Email Address is empty");
            return false;
        }
        
        boolean testEmail;
        Pattern patternEmail;
        Matcher matcherEmail;
        final String email_pattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        patternEmail = Pattern.compile(email_pattern);
        matcherEmail = patternEmail.matcher(email);
        testEmail = matcherEmail.matches();
        if(!testEmail){
            this.showMsg("Email Format is incorrect");
            return false;
        }
        
        if (pswd.equals("")) {
            this.showMsg("Password is empty");
            return false;
        }
        if (cpswd.equals("")) {
            this.showMsg("Confirm Password is empty");
            return false;
        }
        if (phno.equals("")) {
            this.showMsg("Phone Number is empty");
            return false;
        }
        
        boolean testPhno;
        Pattern patternPhno;
        Matcher matcherPhno;
        final String phno_pattern = "\\d{10}";
        patternPhno = Pattern.compile(phno_pattern);
        matcherPhno = patternPhno.matcher(phno);
        testPhno = matcherPhno.matches();
        if(!testPhno){
            this.showMsg("Phone Number should be of 10 digits");
            return false;
        }
        
        if (!(pswd.equals(cpswd))) {
            this.showMsg("Password and Confirm Password should match");
            return false;
        }
        return true;
    }

    private void paneChangedSetUI(int index) {
        switch (index) {
            case 0:
                add_c_fname.setText("");
                add_c_lname.setText("");
                add_c_email.setText("");
                add_c_pswd.setText("");
                add_c_cpswd.setText("");
                add_c_phno.setText("");
                break;

            case 1:
                List<User_Model> coordinators = controller.getAllCoordinators();
                if (!coordinators.isEmpty()) {
                    del_c_name.removeAllItems();
                    for (User_Model coordinator : coordinators) {
                        del_c_name.addItem(coordinator);
                    }
                }
                break;
        }
    }

    private void delCoordinatorSetUI() {
        User_Model selectedCoordinator = (User_Model) del_c_name.getSelectedItem();
        if(selectedCoordinator == null){
            return;
        }
        del_c_id.setText(selectedCoordinator.getUser_id() + "");
        del_c_email.setText(selectedCoordinator.getEmail());
        del_c_phno.setText(selectedCoordinator.getPhno());
        
    }

    public void showMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField add_c_cpswd;
    private javax.swing.JTextField add_c_email;
    private javax.swing.JTextField add_c_fname;
    private javax.swing.JTextField add_c_lname;
    private javax.swing.JFormattedTextField add_c_phno;
    private javax.swing.JPasswordField add_c_pswd;
    private javax.swing.JButton btn_c_register;
    private javax.swing.JButton btn_del_coordinator;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField del_c_email;
    private javax.swing.JTextField del_c_id;
    private javax.swing.JComboBox del_c_name;
    private javax.swing.JTextField del_c_phno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
