/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.Game_Controller;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import models.Game_Model;

/**
 *
 * @author MANALI
 */

public class Student_View extends javax.swing.JFrame {

    /**
     * Creates new form Student_View
     */
    public Game_Controller controller = null;
    
    private String game_name;
    private int game_id, game_players, game_duration, user_id;
    
    public Student_View() {
        controller = new Game_Controller();
        controller.studform = this;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Student_View(int uid) {
        controller = new Game_Controller();
        controller.studform = this;
        user_id = uid;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        s_select_game = new javax.swing.JComboBox();
        btn_add_selected_game = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_selected_game = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_view_selected_games = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        del_selected_game_name = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        del_selected_game_players = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        del_selected_game_duration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_del_selected_game = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("Sports Management System");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name:");

        s_select_game.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s_select_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_select_gameActionPerformed(evt);
            }
        });

        btn_add_selected_game.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_add_selected_game.setText("Add");
        btn_add_selected_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_selected_gameActionPerformed(evt);
            }
        });

        tbl_selected_game.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_selected_game.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game", "No. of Players", "Time Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_selected_game.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_selected_game);
        if (tbl_selected_game.getColumnModel().getColumnCount() > 0) {
            tbl_selected_game.getColumnModel().getColumn(0).setResizable(false);
            tbl_selected_game.getColumnModel().getColumn(1).setResizable(false);
            tbl_selected_game.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(s_select_game, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_add_selected_game, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(s_select_game, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add_selected_game))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Select Games To Participate In", jPanel1);

        tbl_view_selected_games.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game Name", "No. of Players", "Time Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_view_selected_games.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_view_selected_games);
        if (tbl_view_selected_games.getColumnModel().getColumnCount() > 0) {
            tbl_view_selected_games.getColumnModel().getColumn(0).setResizable(false);
            tbl_view_selected_games.getColumnModel().getColumn(1).setResizable(false);
            tbl_view_selected_games.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View Your Games", jPanel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Select Your Game:");

        del_selected_game_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        del_selected_game_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_selected_game_nameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("No. of Players:");

        del_selected_game_players.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Time Duration:");

        del_selected_game_duration.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("mins");

        btn_del_selected_game.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_del_selected_game.setText("Delete");
        btn_del_selected_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_del_selected_gameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(del_selected_game_name, 0, 169, Short.MAX_VALUE)
                                .addComponent(del_selected_game_players))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(del_selected_game_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_del_selected_game, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(del_selected_game_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(del_selected_game_players, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(del_selected_game_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btn_del_selected_game)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Your Game", jPanel3);

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel3.setText("Select Games & View Details");

        btn_logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addComponent(btn_logout)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_select_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_select_gameActionPerformed
        // TODO add your handling code here:
        selectGameSetUI();
    }//GEN-LAST:event_s_select_gameActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        System.out.println("Tab changed to: " + sourceTabbedPane.getTitleAt(index));
        paneChangedSetUI(index);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btn_add_selected_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_selected_gameActionPerformed
        // TODO add your handling code here:
        
        if(controller.addStudentGame(user_id,game_id)){
            DefaultTableModel model = (DefaultTableModel)tbl_selected_game.getModel();
            model.addRow(new Object[]{game_name, game_players, game_duration});
        }
    }//GEN-LAST:event_btn_add_selected_gameActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        Login_View login=new Login_View();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void del_selected_game_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_selected_game_nameActionPerformed
        // TODO add your handling code here:
        delSelectedGameSetUI();
    }//GEN-LAST:event_del_selected_game_nameActionPerformed

    private void btn_del_selected_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_del_selected_gameActionPerformed
        // TODO add your handling code here:
        Game_Model selectedGame = (Game_Model)del_selected_game_name.getSelectedItem();
        controller.deleteSelectedGame((Game_Model)del_selected_game_name.getSelectedItem(),selectedGame.getGame_id(),user_id);
        System.out.println((Game_Model)del_selected_game_name.getSelectedItem());
        del_selected_game_name.removeItemAt(del_selected_game_name.getSelectedIndex());
    }//GEN-LAST:event_btn_del_selected_gameActionPerformed

    private void paneChangedSetUI(int index) {
        switch(index){                
            case 0:
                List<Game_Model> games = controller.getAllGames();
                if(!games.isEmpty()){
                    s_select_game.removeAllItems();
                    for(Game_Model game: games){
                        s_select_game.addItem(game);
                    }
                }
                break;  
                
            case 1:
                List<Game_Model> stud_games = controller.getStudentGames(user_id);
                DefaultTableModel aModel = new DefaultTableModel() {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };
                Object[] tableColumnNames = new Object[3];
                tableColumnNames[0] = "Game Name";
                tableColumnNames[1] = "No. of Players";
                tableColumnNames[2] = "Game Duration";
                aModel.setColumnIdentifiers(tableColumnNames);
                Object[] objects = new Object[3];
                if(!stud_games.isEmpty()){
                    for(Game_Model stud_game: stud_games)
                    {
                        objects[0] = stud_game.getGame_name();
                        objects[1] = stud_game.getNo_of_players();
                        objects[2] = stud_game.getGame_duration();
                        aModel.addRow(objects);
                    }
                    tbl_view_selected_games.setModel(aModel);
                    tbl_view_selected_games.repaint();
                }
                break;
                
            case 2:
                List<Game_Model> stud_games1 = controller.getStudentGames(user_id);
                if(!stud_games1.isEmpty()){
                    del_selected_game_name.removeAllItems();
                    for(Game_Model game2: stud_games1){
                        del_selected_game_name.addItem(game2);
                    }
                }
                break;
        }
    }
    
    private void selectGameSetUI() {
        Game_Model selectedGame = (Game_Model)s_select_game.getSelectedItem();
        if(selectedGame==null){
            return;
        }
        game_id = selectedGame.getGame_id();
        game_name = selectedGame.getGame_name();
        game_players = selectedGame.getNo_of_players();
        game_duration = selectedGame.getGame_duration();
    }
    
    private void delSelectedGameSetUI() {
        Game_Model selectedGame1 = (Game_Model)del_selected_game_name.getSelectedItem();
        if(selectedGame1 == null){
            return;
        }
        del_selected_game_players.setText(selectedGame1.getNo_of_players()+"");
        del_selected_game_duration.setText(selectedGame1.getGame_duration()+"");
    
    }

    
    public void showMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_selected_game;
    private javax.swing.JButton btn_del_selected_game;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField del_selected_game_duration;
    private javax.swing.JComboBox del_selected_game_name;
    private javax.swing.JTextField del_selected_game_players;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox s_select_game;
    private javax.swing.JTable tbl_selected_game;
    private javax.swing.JTable tbl_view_selected_games;
    // End of variables declaration//GEN-END:variables

}
